server:
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 20s
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#    properties:
#      hibernate:
#        format_sql: true
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:23306/shopping?serverTimezone=UTC&characterEncoding=UTF-8
      username: shopping-svc
      password: shopping-pass
  flyway:
    user: shopping-svc
    password: shopping-pass
    schemas: shopping
    url: jdbc:mysql://localhost:23306/shopping?serverTimezone=UTC&characterEncoding=UTF-8
    enabled: true

#  h2:
#    console:
#      enabled: true
#      path: /h2-console

  # Redis
  redis:
    host: localhost
    port: 6379

  # Swagger
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  config: classpath:logback-local.xml
#  level:
#    org:
#      hibernate:
#        type:
#          descriptor:
#            sql: trace

jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHN
