version: "3.7"
services:
  shopping-db:
    image: mysql:8.0
    ports:
      - "23306:3306"
    environment:
      - MYSQL_DATABASE=shopping
      - MYSQL_ROOT_PASSWORD=root-pass
      - MYSQL_USER=shopping-svc
      - MYSQL_PASSWORD=shopping-pass
      - TZ=UTC
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --lower_case_table_names=1
    volumes:
      - ./mysql:/var/lib/mysql