version: "3.7"
services:
  kmong-db:
    image: mysql:8.0
    ports:
      - "13306:3306"
    environment:
      - MYSQL_DATABASE=kmong
      - MYSQL_ROOT_PASSWORD=root-pass
      - MYSQL_USER=kmong-svc
      - MYSQL_PASSWORD=kmong-pass
      - TZ=UTC
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --lower_case_table_names=1
    volumes:
      - ./mysql:/var/lib/mysql